// File:
//   - json.rs
// Path:
//   - src/p3d/src/adapters/driven/json.rs
//
// Copyright:
//   - Copyright (c) 2026 Alberto Villa Osorno.
// SPDX-License-Identifier:
//   - MIT
// Confidential:
//   - false
// License-File:
//   - LICENSE
// Path-Rule:
//   - All paths in this header are repository-root relative.
//
// Boundary-Contract:
// - Owns:
//   - Lossless JSON string-content escaping for P3D adapter renderers.
// - Must-Not:
//   - Render complete JSON documents or replace source characters.
// - Allows:
//   - Encode JSON string delimiters, backslashes, and control characters.
// - Split-When:
//   - Split when typed JSON document rendering gains independent policy.
// - Merge-When:
//   - Another P3D adapter owns identical JSON string escaping.
// - Summary:
//   - Canonical JSON text escaping for P3D extraction adapters.
// - Description:
//   - Preserves decoded source text while producing valid JSON string content.
// - Usage:
//   - Imported privately by P3D component and expression serializers.
// - Defaults:
//   - Every Unicode scalar is preserved or losslessly escaped.
//
// ADRs:
// - docs/adr/pipeline/extraction/extraction-provenance-and-manifest-linkage.md
//
// Large file:
//   - false
//

//! Canonical lossless JSON string-content escaping for P3D adapters.

/// Escape string content for insertion between JSON quotation marks.
pub(super) fn escape_json(value: &str) -> String {
    shar_json_text::escape(value)
}

/// Render one floating-point JSON value while preserving valid finite text.
pub(super) fn render_f32(
    value: f32,
    finite_rendering: String,
) -> String {
    if value.is_finite() {
        finite_rendering
    } else {
        String::from("null")
    }
}

/// Validate one complete JSON document before adapter publication.
///
/// # Errors
///
/// Returns a P3D error when the generated bytes are not one valid JSON value.
pub(super) fn validate_document(
    bytes: &[u8],
    label: &str,
) -> Result<(), crate::P3dError> {
    serde_json::from_slice::<serde_json::Value>(bytes)
        .map(|_value| ())
        .map_err(
            |error| {
                crate::P3dError::invalid_source(
                    format!("generated JSON is invalid for {label}: {error}"),
                )
            },
        )
}

/// Validate every nonempty row in one generated JSONL document.
///
/// # Errors
///
/// Returns a P3D error when one generated row is not valid JSON.
pub(super) fn validate_json_lines(
    text: &str,
    label: &str,
) -> Result<(), crate::P3dError> {
    for (index, line) in text
        .lines()
        .enumerate()
        .filter(
            |(_index, line)| {
                !line
                    .trim()
                    .is_empty()
            },
        )
    {
        let _value = serde_json::from_str::<serde_json::Value>(line).map_err(
            |error| {
                crate::P3dError::invalid_source(
                    format!(
                        "generated JSONL row {} is invalid for {label}: \
                         {error}",
                        index.saturating_add(1),
                    ),
                )
            },
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{render_f32, validate_document, validate_json_lines};

    #[test]
    fn non_finite_floats_render_as_json_null() {
        assert_eq!(
            render_f32(
                f32::NAN,
                String::from("NaN"),
            ),
            "null"
        );
        assert_eq!(
            render_f32(
                f32::INFINITY,
                String::from("inf"),
            ),
            "null"
        );
        assert_eq!(
            render_f32(
                2.5,
                String::from("2.500"),
            ),
            "2.500"
        );
    }

    #[test]
    fn rejects_raw_controls_and_accepts_escaped_controls() {
        let quote = char::from(34);
        let slash = char::from(92);
        let nul = char::from(0);
        let raw = format!("{{{quote}name{quote}:{quote}bad{nul}value{quote}}}");
        let escaped = format!(
            "{{{quote}name{quote}:{quote}good{slash}u0000value{quote}}}"
        );
        let first_row = format!("{{{quote}row{quote}:1}}");
        let second_row = format!("{{{quote}row{quote}:2}}");
        let rows = format!(
            "{first_row}
{second_row}
"
        );
        assert!(
            validate_document(
                raw.as_bytes(),
                "raw-control",
            )
            .is_err()
        );
        assert!(
            validate_document(
                escaped.as_bytes(),
                "escaped-control",
            )
            .is_ok()
        );
        assert!(
            validate_json_lines(
                &rows, "rows",
            )
            .is_ok()
        );
    }
}
