// Copyright:
//   - Copyright (c) 2026 Alberto Villa Osorno.
// SPDX-License-Identifier:
//   - MIT
// Confidential:
//   - false
// License-File:
//   - LICENSE-MIT
//
// Boundary-Contract:
// - Owns:
//   - Json outbound adapter.
// - Must-Not:
//   - Own unrelated policy, persistence, or external effects.
// - Allows:
//   - Inputs and outputs required by this module boundary.
// - Split-When:
//   - Split when one responsibility gains an independent lifecycle.
// - Merge-When:
//   - Merge when another module owns the identical responsibility.
// - Summary:
//   - Json outbound adapter.
// - Description:
//   - Implements the declared outbound adapter responsibility for p3d.
// - Usage:
//   - Used through the owning function boundary.
// - Defaults:
//   - Invalid or missing inputs fail explicitly.
//

//! Json outbound adapter.

pub(super) fn escape_json(value: &str) -> String {
    shar_json_text::escape(value)
}

/// Render one floating-point JSON value while preserving valid finite text.
pub(super) fn render_f32(value: f32, finite_rendering: String) -> String {
    if value.is_finite() {
        finite_rendering
    } else {
        String::from("null")
    }
}

/// Validate one complete JSON document before adapter publication.
///
/// # Errors
///
/// Returns a P3D error when the generated bytes are not one valid JSON value.
pub(super) fn validate_document(
    bytes: &[u8],
    label: &str,
) -> Result<(), crate::P3dError> {
    serde_json::from_slice::<serde_json::Value>(bytes)
        .map(|_value| ())
        .map_err(|error| {
            crate::P3dError::invalid_source(format!(
                "generated JSON is invalid for {label}: {error}"
            ))
        })
}

/// Validate every nonempty row in one generated JSONL document.
///
/// # Errors
///
/// Returns a P3D error when one generated row is not valid JSON.
pub(super) fn validate_json_lines(
    text: &str,
    label: &str,
) -> Result<(), crate::P3dError> {
    for (index, line) in text
        .lines()
        .enumerate()
        .filter(|(_index, line)| !line.trim().is_empty())
    {
        let _value = serde_json::from_str::<serde_json::Value>(line).map_err(
            |error| {
                crate::P3dError::invalid_source(format!(
                    "generated JSONL row {} is invalid for {label}: \
                         {error}",
                    index.saturating_add(1),
                ))
            },
        )?;
    }
    Ok(())
}

#[cfg(test)]
#[path = "../../../../../tests/formats/p3d/unit/adapter-outbound/json/tests.rs"]
mod tests;
