domain = "tools"
schema_version = 1

[entry.cspell]
path = ".dependencies/validation/bin/cspell.cmd"

[entry.git]
path = ".dependencies/validation/bin/git.cmd"

[entry.markdownlint]
path = ".dependencies/validation/bin/markdownlint.cmd"

[entry.pytest]
path = ".dependencies/validation/bin/pytest.cmd"

[entry.ruff]
path = ".dependencies/validation/bin/ruff.cmd"

[entry.rust_nightly_cargo]
path = ".dependencies/validation/rust/nightly-2026-07-14/bin/cargo.cmd"

[entry.rust_nightly_cargo_clippy]
path = ".dependencies/validation/rust/nightly-2026-07-14/bin/clippy.cmd"

[entry.rust_nightly_cargo_fmt]
path = ".dependencies/validation/rust/nightly-2026-07-14/bin/fmt.cmd"

[entry.rust_stable_cargo]
path = ".dependencies/validation/rust/stable-1.97.1/bin/cargo.cmd"
